[package]
name = "wasmclient"
version = "0.1.0"
authors = ["rewt"]
edition = "2018"

[dependencies.stdweb]
version = "0.4.20"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]